name: CD POI .NET Core

on:
  push:
    branches: [ master ]
    paths: [ apis/poi/**, .github/workflows/CD-apis-poi.yml ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apis/poi 
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/poi
        path: apis/poi/web
        tag_with_sha: true
      env:
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_SERVER: openhacktibi123sql.database.windows.net
        SQL_DBNAME: mydrivingDB

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEPLOYMENT_CREDENTIALS }}

    - name: Package repo authenticate
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Web App GitHubPackage authentication
      uses: Azure/appservice-settings@v1
      with:
        app-name: openhacktibi123poi 
        app-settings-json: |
          [
              {
                  "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                  "value": "${{ secrets.GITHUB_TOKEN }}",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_URL",
                  "value": "https://docker.pkg.github.com",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                  "value": "${{ github.actor }}",
                  "slotSetting": false
              }
          ]
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: openhacktibi123poi
        images: docker.pkg.github.com/${{ github.repository }}/poi:${{ github.sha }}

    - name: On error -> Create issue 
      if: ${{ failure() }}
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });

