name: CD POI .NET Core
env: 
  API_NAME: poi
  DOCKER_FILE_PATH: apis/poi/web
  DEPLOYMENT_PREFIX: openhacktibi123
  DEPLOYMENT_SLOT: production
  DATABASE_NAME: mydrivingDB

on:
  push:
    branches: [ master ]
    paths: [ apis/poi/**, .github/workflows/CD-apis-poi.yml ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env: 

      # for github packages use this

      DOCKER_REGISTRY_SERVER_USERNAME: ${{ github.actor }}
      READ_PACKAGE_TOKEN: ${{ secrets.READ_PACKAGE_TOKEN }}
      WRITE_PACKAGE_TOKEN: ${{ secrets.WRITE_PACKAGE_TOKEN }}

      # for ACR use this and change first step

      # DOCKER_REGISTRY_SERVER_USERNAME: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME}}
      # READ_PACKAGE_TOKEN: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}
      # WRITE_PACKAGE_TOKEN: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    steps:
    - name: Setting dynamic environment variables 
      run: |
        echo ::set-env name=DOCKER_TAG::"$(echo $GITHUB_SHA | cut -c 1-6)"
        echo ::set-env name=DOCKER_REPOSITORY::"$(echo $GITHUB_REPOSITORY/$API_NAME)"
        echo ::set-env name=SQL_SERVER::"$(echo ""$DEPLOYMENT_PREFIX""sql.database.windows.net)"
        echo ::set-env name=DOCKER_REGISTRY_SERVER::"$(echo docker.pkg.github.com/$GITHUB_REPOSITORY_OWNER)"
      # echo ::set-env name=DOCKER_REGISTRY_SERVER::$(echo ""$DEPLOYMENT_PREFIX""acr.azurecr.io)

    - name: Print environment variables 
      run: |
        echo "DOCKER_TAG: $DOCKER_TAG"
        echo "DOCKER_REPOSITORY: $DOCKER_REPOSITORY"
        echo "SQL_SERVER: $SQL_SERVER"
        echo "DOCKER_REGISTRY_SERVER: $DOCKER_REGISTRY_SERVER"
        env

    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ env.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ env.WRITE_PACKAGE_TOKEN }}
        registry: ${{ env.DOCKER_REGISTRY_SERVER }}
        repository: ${{ env.DOCKER_REPOSITORY }}
        path: ${{ env.DOCKER_FILE_PATH }}
        tags: ${{ env.DOCKER_TAG }}
      env:
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_SERVER: ${{ env.SQL_SERVER }} 
        SQL_DBNAME: ${{ env.DATABASE_NAME }}

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEPLOYMENT_CREDENTIALS }}

    # https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build

    # - name: Package repo authenticate
    #   uses: azure/docker-login@v1
    #   with:
    #     login-server: ${{ env.DOCKER_REGISTRY_SERVER }}
    #     username: ${{ env.DOCKER_REGISTRY_SERVER_USERNAME }}
    #     password: ${{ env.READ_PACKAGE_TOKEN }}

    - name: Set Web App GitHubPackage authentication
      uses: Azure/appservice-settings@v1
      with:
        app-name: '${{ env.DEPLOYMENT_PREFIX }}${{ env.API_NAME }}'
        slot-name: ${{ env.DEPLOYMENT_SLOT }}
        app-settings-json: |
          [
              {
                  "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                  "value": "${{ env.READ_PACKAGE_TOKEN }}",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_URL",
                  "value": "https://${{ env.DOCKER_REGISTRY_SERVER }}",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                  "value": "${{ env.DOCKER_REGISTRY_SERVER_USERNAME }}",
                  "slotSetting": false
              },
              {
                "name": "SQL_DBNAME",
                "value": "${{ env.DATABASE_NAME }}",
                "slotSetting": false
              },
              {
                "name": "SQL_PASSWORD",
                "value": "${{ secrets.SQL_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "SQL_SERVER",
                "value": "${{ env.DEPLOYMENT_PREFIX }}sql.database.windows.net",
                "slotSetting": false
              },
              {
                "name": "SQL_USER",
                "value": "${{ secrets.SQL_USER }}",
                "slotSetting": false
              },
              {
                "name": "WEBSITES_PORT",
                "value": "8080",
                "slotSetting": false
              }
          ]

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: '${{ env.DEPLOYMENT_PREFIX }}${{ env.API_NAME }}'
        images: ${{ env.DOCKER_REGISTRY_SERVER }}/${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }}
        slot-name: ${{ env.DEPLOYMENT_SLOT }}

    - name: On error -> Create issue 
      if: ${{ failure() }}
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });

