name: CI UserProfile nodejs

on:
  push:
    branches: [ master ]
    paths: [ apis/userprofile/**, .github/workflows/CI-apis-userprofile.yml ]
  pull_request:
    branches: [ master ]
    paths: 
      - apis/userprofile/**
      - .github/workflows/CI-apis-userprofile.yml

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apis/userprofile 
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install dependencies
      run: npm install
      
    - name: Test Userprofile
      run: npm run test --if-exists

    - name: On error -> Create issue 
      if: ${{ failure() }}
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
