name: CI/CD Trips go

on:
  push:
    branches: [ master ]
    paths: [ apis/trips/**, .github/workflows/CI-apis-trip.yml ]
  pull_request:
    branches: [ master ]
    paths: 
      - apis/trips/**
      - .github/workflows/CI-apis-trip.yml

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apis/trips 
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Setup golang
      uses: actions/setup-go@v1
      with:
        go-version: '^1.13.1'

    - name: Test trips
      run: go test ./tests

    - name: Build Docker image
      uses: docker/build-push-action@v1
      env:
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_SERVER: openhacktibi123sql.database.windows.net
        SQL_DBNAME: mydrivingDB
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/trips
        path: apis/trips
        tag_with_ref: true
        
    - name: On error -> Create issue 
      if: ${{ failure() }}
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
