name: CI/CD POI .NET Core

on:
  push:
    branches: [ master ]
    paths: [ apis/poi/**, .github/workflows/CI-apis-poi.yml ]
  pull_request:
    branches: [ master ]
    paths: 
      - apis/poi/**
      - .github/workflows/CI-apis-poi.yml

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apis/poi 
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.801

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build POI
      run: dotnet build --configuration Release --no-restore
      
    - name: Test POI
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Build Docker image
      uses: docker/build-push-action@v1
      env:
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_SERVER: openhacktibi123sql.database.windows.net
        SQL_DBNAME: mydrivingDB
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/poi
        path: apis/poi/web
        tag_with_ref: true

    - name: Package repo authenticate
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        publish-profile: ${{ secrets.POI_AZURE_WEBAPP_PUBLISH_PROFILE }}
        app-name: openhackl5u1jy65poi
        images: docker.pkg.github.com/${{ github.repository }}/poi:${{ github.ref }}

    - name: On error -> Create issue 
      if: ${{ failure() }}
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
